#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EA...
      - ssh-rsa AAAAB3NzaC1yc2EA...
      - ssh-rsa AAAAB3NzaC1yc2EA...