---
apiVersion: v1
kind: Pod
metadata:
  name: web-app
  namespace: monitoring
spec:
  containers:
  - name: simpleapp
    image: chaltsev/simpleapp:v1
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: monitoring
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: web-app